version: '3'

services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "3001:3001"
    volumes:
      # Persist dynamic shape data (JSON files added at runtime)
      - ./server/data:/app/server/data
    environment:
      - NODE_ENV=production

  # client service removed; server now serves static build. Uncomment to run standalone HTTPS static container.
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8443:443"
  #   environment:
  #     - NODE_ENV=production
  #   depends_on:
  #     - server
